name: diff4sbi
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=23.3.1=py310h06a4308_0
  - python=3.10.0=h12debd9_5
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py310h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - altair==5.2.0
      - altair-data-server==0.4.1
      - altair-saver==0.5.0
      - altair-viewer==0.4.0
      - arviz==0.17.1
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - autograd==1.6.2
      - certifi==2024.2.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - comm==0.2.2
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==3.0.9
      - dask==2024.3.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - deneb==1.0.1
      - diffeqtorch==1.0.0
      - distributed==2024.3.1
      - elfi==0.8.7
      - entrypoints==0.4
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - filelock==3.13.3
      - flatlatex==0.15
      - fonttools==4.50.0
      - fsspec==2024.3.1
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - gpy==1.13.1
      - greenlet==3.0.3
      - grpcio==1.62.1
      - h11==0.14.0
      - h5netcdf==1.3.0
      - h5py==3.10.0
      - idna==3.6
      - importlib-metadata==7.1.0
      - ipykernel==6.29.3
      - ipyparallel==8.7.0
      - ipython==8.22.2
      - jabbar==0.0.16
      - jax==0.4.25
      - jaxlib==0.4.25+cuda12.cudnn89
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - julia==0.6.2
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - lampe==0.8.2
      - locket==1.0.0
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - mergedeep==1.3.4
      - ml-dtypes==0.3.2
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multipledispatch==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nflows==0.14
      - numdifftools==0.9.41
      - numpy==1.24.4
      - numpyro==0.14.0
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvcc-cu12==12.4.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu12==8.9.7.29
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - opt-einsum==3.3.0
      - outcome==1.3.0.post0
      - packaging==24.0
      - pandas==2.2.1
      - paramz==0.9.6
      - parso==0.8.3
      - partd==1.4.1
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.2.0
      - portpicker==1.6.0
      - pot==0.9.3
      - prompt-toolkit==3.0.43
      - protobuf==5.26.0
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyabc==0.12.13
      - pyabcranger==0.0.70
      - pygments==2.17.2
      - pyknos==0.15.2
      - pyparsing==3.1.2
      - pyro-api==0.1.2
      - pyro-ppl==1.9.0
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - redis==5.0.3
      - referencing==0.34.0
      - regex==2023.12.25
      - rpds-py==0.18.0
      - sbi==0.21.0
      - sbibm==1.1.0
      - scikit-learn==1.4.1.post1
      - scipy==1.11.4
      - seaborn==0.13.2
      - selenium==4.18.1
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sqlalchemy==2.0.29
      - stack-data==0.6.3
      - sympy==1.12
      - tblib==3.0.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.4.0
      - toolz==0.12.1
      - torch==2.1.0+cu118
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - trio==0.25.0
      - trio-websocket==0.11.1
      - triton==2.1.0
      - tueplots==0.0.14
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - vega-datasets==0.9.0
      - wcwidth==0.2.13
      - werkzeug==3.0.1
      - wsproto==1.2.0
      - xarray==2024.2.0
      - xarray-einstats==0.7.0
      - zict==3.0.0
      - zipp==3.18.1
      - zuko==1.1.0
# prefix: <path_to_env>